# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dndpimp', '0005_auto_20170903_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name_plural': 'parties'},
        ),
    ]
